- name: Apply critical patches
  run: |
    # Инициализация структуры Buildozer
    buildozer android clean
    buildozer android update
    
    # Проверка существования патча
    if [ ! -f "libffi-symbol-uscore.patch" ]; then
      echo "❌ libffi-symbol-uscore.patch не найден!"
      exit 1
    fi
    
    # Применение патча
    LIBFFI_CONFIGURE=$(find .buildozer/android/platform -name "configure.ac")
    if [ -z "$LIBFFI_CONFIGURE" ]; then
      echo "❌ configure.ac не найден!"
      exit 1
    fi
    
    patch -d $(dirname "$LIBFFI_CONFIGURE") -p1 < libffi-symbol-uscore.patch || true
    
    # Пересборка libffi
    LIBFFI_PATH=$(find .buildozer -path "*libffi/arm64-v8a*" -type d -name "libffi" | head -1)
    cd "$LIBFFI_PATH"
    autoreconf -fiv
    aclocal
    automake --add-missing
    autoconf
