name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.1.8937393

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              autoconf automake libtool \
              gettext pkg-config make \
              gcc g++ unzip flex bison \
              libffi-dev texinfo help2man \
              openjdk-17-jdk cython3 \
              libltdl-dev zlib1g-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36 kivy==2.3.0

      - name: Prepare environment
        run: |
          rm -rf .buildozer/android/platform/python-for-android
          git clone --branch 2024.05.06 \
            https://github.com/kivy/python-for-android.git \
            .buildozer/android/platform/python-for-android

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '25.1.8937393'
          build-tools-version: '34.0.0'
          cmake-version: '3.22.1'

      - name: Apply libffi patch
        run: |
          cd .buildozer/android/platform/python-for-android
          git apply ../../../../libffi-symbol-uscore.patch || true
          autoreconf --install
          aclocal
          autoheader
          automake --add-missing
          libtoolize --force
          autoreconf -fiv

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android release \
            -- \
            --package-type apk \
            --gradle-version 8.3 \
            --depend "androidx.core:core-ktx:1.12.0" \
            --depend "com.android.tools.build:gradle:8.3.0"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
