name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.2.11394342

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              autoconf automake libtool \
              gettext pkg-config make \
              gcc g++ unzip flex bison \
              libffi-dev texinfo help2man \
              openjdk-17-jdk cython3 \
              libltdl-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Prepare environment
        run: |
          rm -rf .buildozer bin
          buildozer android update

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '26.2.11394342'
          build-tools-version: '34.0.0'
          cmake-version: '3.22.1'

      - name: Patch libffi
        run: |
          LIBFFI_PATH=$(find .buildozer -path "*libffi/arm64-v8a*" -type d -name "libffi" | head -1)
          cd "$LIBFFI_PATH"
          
          # Critical patches for modern autoconf
          sed -i 's/AC_TRY_LINK/AC_LINK_IFELSE/g' configure.ac
          sed -i 's/AC_TRY_COMPILE/AC_COMPILE_IFELSE/g' configure.ac
          sed -i 's/AC_HELP_STRING/AS_HELP_STRING/g' configure.ac
          sed -i 's/AC_PROG_LD/AC_PROG_LD_GNU/g' configure.ac
          sed -i 's/AC_TRY_RUN/AC_RUN_IFELSE/g' configure.ac
          echo "m4_pattern_allow([LT_SYS_SYMBOL_USCORE])" >> configure.ac
          
          # Regenerate config files
          autoreconf -fiv
          aclocal -I m4 --force
          libtoolize --force --copy
          autoheader
          automake --add-missing --copy --force-missing
          autoconf --force

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
